### ISSUE TITLE
Retriving the data.

### ISSUE THREAD

**Issue by jdoig** [brpandey/merkel#1]
Hi, whats the best/quickest way to just get the underlying data in the tree?

I'm interested in using this library to validate data is in-sync across nodes, but when a node first comes online it seems the best way to get it up to speed is chunk and send just the underlying data then let the periodic "self healing" process use the Merkle tree to detect errors.

Would I be best looping over keys then performing lookups, walking the tree down to each node, or just storing my data alongside it's Merkle tree (this seems expensive, space wise)

**Comment by brpandey** [comment]
I'm traveling at the moment let me get back to you

**Comment by brpandey** [comment]
I'm sincerely sorry this had to take so long, for such a quick enhancement

`
iex> l = [{"zebra", 23}, {"daisy", "932"}, {"giraffe", 29}, {"anteater", "12"}, {"walrus", 49}]
`
`
iex> m1 = Merkel.new(l)
`
`
iex> Merkel.to_list(m1)
[
  {"anteater", "12"},
  {"daisy", "932"},
  {"giraffe", 29},
  {"walrus", 49},
  {"zebra", 23}
]
`

**Comment by brpandey** [comment]
Just added Merkel.to_list/1
